name: Pull Request
on:
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Trunk
        run: curl https://get.trunk.io -fsSL | bash

      - name: Testing
        uses: trunk-io/breakpoint@92ca21db721a9617c5eeff73b2c671292470d6fb
        env:
          TRUNK_API_ADDRESS: api.trunk-staging.io:8443
          TRUNK_CLI_VERSION: 1.10.1-beta.31
        with:
          breakpoint_id: run-tests
          run: ./run_tests.sh
          trunk_token: ${{ secrets.TRUNK_TOKEN }}
