name: Pull Request
on:
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Trunk
        run: curl https://get.trunk.io -fsSL | bash

      - name: Testing
        uses: trunk-io/breakpoint@v1
        env:
          TRUNK_API_ADDRESS: api.trunk-staging.io:8443
          TRUNK_CLI_VERSION: 1.9.2-beta.14
        with:
          breakpoint_id: unit-tests
          command: ./run_tests.sh
          trunk_token: ${{ secrets.INPUT_TRUNK_TOKEN }}
