name: Pull Request
on:
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Testing
        uses: trunk-io/breakpoint@v1
        with:
          breakpoint_id: run-tests
          command: ./run_tests.sh
          trunk_token: ${{ secrets.INPUT_TRUNK_TOKEN }}
