name: Pull Request
on:
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Trunk
        run: curl https://get.trunk.io -fsSL | bash

      - name: Testing
        run: trunk breakpoint --id="Demo" -- bash ./test.sh
        env:
          TRUNK_GITHUB_CONTEXT: ${{ toJSON(github) }}
          INPUT_TRUNK_TOKEN: ${{ secrets.INPUT_TRUNK_TOKEN }}
          SHELL: bash
          GH_TOKEN: ${{ github.token }}
