name: Pull Request
on:
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Trunk
        run: curl https://get.trunk.io -fsSL | bash

      - name: Testing
        uses: trunk-io/breakpoint@v1
        with:
          breakpoint_id: Demo
          command: bash ./test.sh
          trunk_token: ${{ secrets.INPUT_TRUNK_TOKEN }}
