name: Pull Request
on:
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup trunk
        uses: trunk-io/trunk-action/setup@c368dc0c57ec3eb9a03b8db7fe4f61d8d13eb999

      - name: Checkout
        uses: actions/checkout@v2

      - name: Testing
        uses: trunk-io/breakpoint@v1
        with:
          breakpoint-id: run-tests
          run: ./run_tests.sh
          trunk-token: ${{ secrets.TRUNK_DEBUGGER_TOKEN }}
          org: trunk
