name: Pull Request
on:
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Testing code
        uses: trunk-io/breakpoint@d6ddac31f4ab33a271693d50ac8b342af16195c9
        with:
          breakpoint-id: run-tests
          run: ./run_tests.sh
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
